version: 2.1

jobs:
  install-dependencies:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Update or install PNPM
          command: 'sudo npm install -g pnpm'
      - restore_cache:
          key: app-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: 'npm install'
      - persist_to_workspace:
          root: .
          paths:
            - .
  vercel-deploy:
    build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Install CLI Vercel
          command: 'sudo npm install -g vercel'
      - attach_workspace:
          at: .
      - run:
          name: Vercel Prod Deploy
          command: vercel --prod --build-env REACT_APP_BASEURL=https://rickandmortyapi.com/api/ --name $VERCEL_PROJECT_NAME --scope $VERCEL_SCOPE --token=$VERCEL_TOKEN --yes
workflows:
  version: 2
  deploy-reactapp:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - develop
      - vercel-deploy:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - develop